### ISSUE TITLE
Build error for Boruvka on Mac -- endian.h

### ISSUE THREAD

**Issue by rpgoldman** [panda-planner-dev/pandaPIgrounder#4]
Trying to build pandaPIgrounder on the Mac, I am unable to because of this error building boruvka:

    CC=/opt/homebrew/opt/gcc/bin/gcc-13 make

Here's the specific error:

```
/opt/homebrew/opt/gcc/bin/gcc-13 -O3 -Wall -pedantic -std=gnu99 -ffast-math -I. -c -o .objs/msg-schema.o src/msg-schema.c
src/msg-schema.c:17:10: fatal error: endian.h: No such file or directory
   17 | #include <endian.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [.objs/msg-schema.o] Error 1
```

Note that I had to do this with Homebrew's `gcc` because the C compiler Apple ships can't handle implicitly defined functions, as discussed in issue #2 

I know I should be posting this to Boruvka, but gitlab.com is down, and I wanted to write this up here while waiting for it to come back up.

**Comment by galvusdamor** [comment]
Apparently this include of `#include <endian.h>` within boruvka is not necessary -- at least locally on my machine. As a test, I would try to remove it and see whether the code compiles without it under MacOS as well.

Getting rid of this include in a clean way is a little complicated - as it is code inside a submodule that is located in a submodule. I have added two patches - one for cpddl and one for boruvka itself. The patch for cpddl will automatically apply the one for boruvka in the build process.

I have committed the changes and updated the build instructions. @rpgoldman can you try whether it works on your machine?

**Comment by rpgoldman** [comment]
`endian.h` is not needed on my machine. I have a couple of other Mac-related fixes to the grounder that I can share.  I'm still having trouble building locally, likely because there's a bunch of stuff that tries to build static libraries, which I believe MacOS doesn't like.

**Comment by rpgoldman** [comment]
The current version builds on my (M1/ARM64) Mac, but only if I use `gcc` (from Homebrew).  If I try to use `clang` from Apple, it does not build.

So this looks fixed, thanks!
