### ISSUE TITLE
pandaPIgrounder fails on output from pandaPIparser

### ISSUE THREAD

**Issue by rpgoldman** [panda-planner-dev/pandaPIgrounder#9]
Here is the output from a run of the pandaPIgrounder:

```
# /pandaPIgrounder/pandaPIgrounder debug.panda
General Options
  Print timings: false
  Quiet mode: false
Inference Options
  H2 mutexes: false
  FAM groups: false
Transformation Options
  Add zero-cost no-op to empty methods: true
  Remove duplicate actions: true
  Remove useless literals: true
  Expand abstract tasks with one method: true
  Remove empty method preconditions: true
  Two regularisation: false
  Compile negative SAS variables: false
Runtime Optimisations
  Hierarchy Typing: true
  Future Caching: false
  Static Precondition Checking: false
Output Options
  Panda planner format: true
  HDDL: false
  SAS for Fast Downward (without hierarchy): false
Output Formatting Options
  Output only SAS+ variables: false
  SAS+ delete mode: as input
Reading input from debug.panda.
Input parse error: basic_ios::clear: iostream error
Reached EOF while reading input.
Writing output to standard output.
Writing output to standard output.
Failed to read input data!
```

I'm not sure how to diagnose the parse error from the file `debug.panda`. It's a file that was generated by parsing HDDL that I machine generated from an implementation of the plan-repair by rewriting algorithm of Höller, et al.

The `debug.panda` file is posted in this github gist: https://gist.github.com/rpgoldman/a68d2bdc2cdd0b9371d2c65d39579c76

Thank you for any assistance!

**Comment by rpgoldman** [comment]
This looks like it was a badly constructed domain -- I fixed some bugs in the rewrite code and was able to run the three Panda stages successfully.

On the other hand, it isn't a good thing that the grounder can fail on output from pandaPIparser -- especially not with input it can't parse.  At least it would be better to  fail with a diagnostic message. So I won't delete this issue. But if you don't think it's interesting -- or if it's an issue with the output provided by the parser -- feel free to close it.

**Comment by galvusdamor** [comment]
Yes. See #10
